#include <iostream>
#include <fstream>
#include <sstream>
#include "Lexer/tokenizer.h"
#include "AST/parser.h"
#include "VM/vm.h"
#include "Bytecode/byte.h"

int main(int argc, char *argv[])
{
    if (argc < 2)
    {
        std::cerr << "Usage: cspine <file>\n";
        return 1;
    }

    std::ifstream file(argv[1]);
    if (!file)
    {
        std::cerr << "Could not open file: " << argv[1] << "\n";
        return 1;
    }

    std::stringstream buffer;
    buffer << file.rdbuf();
    std::string source = buffer.str();

    try
    {
        Tokenizer tokenizer(source);
        auto tokens = tokenizer.tokenize();

        tokenizer.show();

        Parser parser(tokens);
        auto ast = parser.parse();

        // parser.show(); // Show AST for debugging

        BytecodeGenerator gen;
        auto bytecode = gen.generate(ast);

        // gen.show(); // Show generated bytecode for debugging

        auto node = ast; // for debugging
        bool leftDone = false;
        std::shared_ptr<ASTNode> currentLevel;
        auto first = true;

        Interpreter vm;
        vm.run(bytecode);
    }
    catch (std::exception &e)
    {
        std::cerr << e.what() << "\n";
        return 1;
    }
}
